### ISSUE TITLE
see output images on Colab

### ISSUE THREAD

**Issue by senemaktas** [dengwirda/inpoly-python#10]
Hi , I would like to try your library.

When I run examples,
```
 python3 example.py --IDnumber=1
  python3 example.py --IDnumber=2
  python3 example.py --IDnumber=3
```
I could not see output images on Colab. I inclıded "%matplotlib inline" it does not work. How can I see it?

thanks.

**Comment by dengwirda** [comment]
Hi @senemaktas, I'd expect `python3 example.py --IDnumber=1` to show the output of the 1st example in a `matplotlib` figure. It sounds like you may be running on a machine that doesn't support visual display.

**Comment by senemaktas** [comment]
> Hi @senemaktas, I'd expect `python3 example.py --IDnumber=1` to show the output of the 1st example in a `matplotlib` figure. It sounds like you may be running on a machine that doesn't support visual display.

Hi, @dengwirda I am including my screenshot here. I have included `%matplotlib inline` because I am using colab. Is it make difference when I run on Google Colab? Thanks.
![Screenshot 2021-07-07 at 15-20-14 Google Colaboratory](https://user-images.githubusercontent.com/30393152/124758171-fb2a1800-df36-11eb-8a04-d9ddf1907b19.png)

**Comment by dengwirda** [comment]
I've not used google's colab, so am not clear on whether it functions in the same way as command-line python. It looks like there's a fair amount of information/help on the site though, so let me know if you find anything out.
