### ISSUE TITLE
Building on Python 3.11

### ISSUE THREAD

**Issue by SnakeCharmed** [dengwirda/inpoly-python#15]
pip install git+https://github.com/dengwirda/inpoly-python.git  errors out with:
inpoly\inpoly_.c(215): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory

Apparently this is well known, e.g.:
https://github.com/cython/cython/issues/4461
and involves longintrepr.h moving from  Include/longintrepr.h to Include/cpython/longintrepr.h. 

Beyond this, I don't know what I'm doing, but I tried:

- Changing the line in inpoly_.c:
  #include "longintrepr.h"
to
  #include "cpython/longintrepr.h"

- Rebuilding things completely with:
 python setup.py build_ext --inplace  

... and neither worked, and I'm already beyond what I really understand.

**Comment by jreniel** [comment]
I also got this error once, but I think doing `pip install cython` fixed it. Could you try that?
Thanks!

**Comment by krober10nd** [comment]
thanks Jaime, yes that worked for me too.

**Comment by dengwirda** [comment]
Resolved by @jreniel.

**Comment by jreniel** [comment]
One small comment, a more thorough solution is to switch the build system to poetry as in https://github.com/dengwirda/inpoly-python/pull/17
