### ISSUE TITLE
pypi and inpoly-python

### ISSUE THREAD

**Issue by krober10nd** [dengwirda/inpoly-python#7]
Hey Darren, 

I've finally found time to do some things that I like :} 

I'd like to use this `inpoly` routine in my Python version of [oceanmesh](https://github.com/CHLNDDEV/oceanmesh) to build signed distance functions and for various other things. 

It'd be a great utility for this to be on `pypi`, that way the CircleCi build system could simply download it and install it with one line.

**Comment by dengwirda** [comment]
Hopefully the [pypi links, etc](https://pypi.org/project/inpoly/) are working already(?), let me know if you have any issues.

**Comment by krober10nd** [comment]
Odd, CircleCI is throwing problems...says it can't find numpy which is odd.

https://app.circleci.com/pipelines/github/CHLNDDEV/oceanmesh/98/workflows/b47671e8-c357-43f3-8f41-01c75f4f4f00/jobs/195

I just put the `inpoly` package another item on the `install_requires` in my setup.cfg file.

**Comment by krober10nd** [comment]
I think it's because the import for numpy is inside the setup.py, which is necessary for the Cython stuff. However, it seems I need to control the order of the installation of packages in order to work around that.

**Comment by krober10nd** [comment]
working just fine. I just had to install numpy prior to installing the other dependencies in the config.yml for CI. 

https://github.com/CHLNDDEV/oceanmesh/blob/msh_clean/.circleci/config.yml
